// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAC0Mjf1Aq8-7xtI_7k9DtcN8cT6d3v3Y',
    appId: '1:60187864643:web:9e99332b8049f93a012ef6',
    messagingSenderId: '60187864643',
    projectId: 'murojaatapp',
    authDomain: 'murojaatapp.firebaseapp.com',
    storageBucket: 'murojaatapp.appspot.com',
    measurementId: 'G-WL29Y7QWZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoi6mYKA4neeLPlmIwNGpchT5wrjekwk',
    appId: '1:60187864643:android:5a72f2f45d48b1d4012ef6',
    messagingSenderId: '60187864643',
    projectId: 'murojaatapp',
    storageBucket: 'murojaatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9v8Ib4CaCZ7ZA8qhymUKBv5IpqyuDbPI',
    appId: '1:60187864643:ios:62b3bded26e40593012ef6',
    messagingSenderId: '60187864643',
    projectId: 'murojaatapp',
    storageBucket: 'murojaatapp.appspot.com',
    iosBundleId: 'com.example.xodimlarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9v8Ib4CaCZ7ZA8qhymUKBv5IpqyuDbPI',
    appId: '1:60187864643:ios:433dda17a72b99f0012ef6',
    messagingSenderId: '60187864643',
    projectId: 'murojaatapp',
    storageBucket: 'murojaatapp.appspot.com',
    iosBundleId: 'com.example.xodimlarapp.RunnerTests',
  );
}
